services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: lld
      POSTGRES_PASSWORD: lld
      POSTGRES_DB: banking
    ports:
      - "5441:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lld"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6391:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
